// <auto-generated />
namespace WebGames.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class no_fk_user_in_scores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(no_fk_user_in_scores));
        
        string IMigrationMetadata.Id
        {
            get { return "201704231911411_no_fk_user_in_scores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
