// <auto-generated />
namespace WebGames.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Last_Game_Score_Names_Fixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Last_Game_Score_Names_Fixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201704202023330_Last_Game_Score_Names_Fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
